### PR TITLE
More edits to the workflow notebook

### PR DESCRIPTION
**Pull request by wlandau**
1. Disable `DT` pagination when printing `drake` plans.
2. Caution users about [redundant serialization](https://github.com/richfitz/storr/issues/77#issuecomment-476275570) and suggest a temporary workaround.

cc @edgararuiz

### CODE REVIEW

**Comment by wlandau** [comment]
I should probably spell out the more efficient / less convenient approach using `file_in()`/`file_out()` to track saved HDF5 model files. New commits forthcoming...

**Comment by wlandau** [comment]
In https://github.com/sol-eng/tensorflow-w-r/pull/8/commits/47ddb29eead6abaf75cd05eccb26b031c57ef28d, I propose an alternative workaround to address https://github.com/richfitz/storr/issues/77#issuecomment-476275570. I think the optimal choice depends on whether serialization really is a bottleneck versus how much of a headache `file_in()` and `file_out()` become if we use them for every single model in the plan. I do not have an overall recommendation, so I would prefer to showcase both if that sounds good.

**Comment by edgararuiz-zz** [comment]
Yes, showcasing both sound good.  Should we merge this PR or do you have more commits to it forthcoming?

**Comment by wlandau** [comment]
Glad we agree, Edgar. I will revisit this when I learn more about how these options play out in practice. I looked over the report again, and it is ready to merge from my end.

**Comment by wlandau** [comment]
Thanks!

**Pull request merged**
